world: world
auto-start: false
reset-border-on-stop: true
start-radius: 400
phases:
  - radius: 400
    duration: 100    # 스톰 축소 시간
    damage: 0.3
    warn: 5.0
    delay: 400       # 준비 시간
    color: PURPLE
  - radius: 250
    duration: 100
    damage: 0.5
    warn: 5.0
    delay: 400
    color: BLUE
  - radius: 150
    duration: 80
    damage: 0.8
    warn: 5.0
    delay: 300
    color: GREEN
  - radius: 80
    duration: 70
    damage: 1.0
    warn: 5.0
    delay: 250
    color: YELLOW
  - radius: 30
    duration: 60
    damage: 1.5
    warn: 5.0
    delay: 200
    color: RED

center:
  x: 0.0
  z: 0.0
